### ISSUE TITLE
s6-svscan shows warning messages on arm32v7/alpine container

### ISSUE THREAD

**Issue by YoitoFes** [skarnet/s6#26] opened 2021-02-22 05:13 UTC
**Platform:** arm32v7/alpine container (Host OS is either Debian 10 amd64 or Raspberry Pi OS arm32)
**s6 version:** 2.10.0.2

When I execute s6-svscan, following warning messages are displayed although the services work fine.

```bash
$ cat /etc/s6/cron/run
#!/bin/sh

exec cron -f -d 8

$ s6-svscan /etc/s6
crond: crond (busybox 1.32.1) started, log level 8
s6-supervise yes: warning: can't happen: timeout while the service is up!
s6-supervise yes: warning: can't happen: timeout while the service is up!
s6-supervise yes: warning: can't happen: timeout while the service is up!
```

s6-2.9.1.0 does not show the messages in the same situation.

**Comment by skarnet** [comment] 2021-02-22 10:06
Known issue, fixed in Alpine edge. (`skalibs-2.10.0.2-r1`)

The problem is that Alpine builds packages with fortify-headers, which until the latest version broke `ppoll()` with musl-1.2 on 32-bit architectures. skalibs has been rebuilt on edge with a fixed fortify-headers; please upgrade it if you can, else it will be available in the next 3.13 bugfix release.

**Closed by skarnet** 2021-02-22 10:06 UTC
