### ISSUE TITLE
A service is not restarted after SIGKILL

### ISSUE THREAD

**Issue by p01arbear** [skarnet/s6#38] opened 2024-07-27 02:39 UTC
Hello.
I have s6 version 2.13.0.0 and s6-overlay 3.2.0.0 from Jun 7 2024.

A supervised service got SIGKILL and is not being restarted after death, even though this behavior is declared as the default in the [docs](https://skarnet.org/software/s6/s6-supervise.html#:~:text=unless%20it%20has%20been%20told%20not%20to). I don't see any information in the docs on how to debug this. Running `s6-svc -U`/`s6-svc -u` before the SIGKILL also doesn't change the behaviour. s6-svstat flags are:

> \# s6-svstat -o up,**wantedup**,normallyup,ready,paused
> true **true** true true false

There is no ./down file in the service directory [to prevent](https://skarnet.org/software/s6/servicedir.html#:~:text=s6-supervise%20will%20not%20automatically%20start%20it) the service from being restarted.

> \#  ls -R MY_SERVICE_DIR
> .:
> event  finish  run  supervise
> ./event:
> ./supervise:
> control  death_tally  lock  status

Logs with S6_VERBOSITY=5 shows nothing:
```
./run: line 28: 282 Killed     s6-setuidgid    <MY_SERVICE_PATH>
s6-rc: info: bringing selected services down
s6-rc: info: service legacy-services: stopping
s6-ipcclient: info: s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-rc: info: service legacy-services successfully stopped
```
How can I make the service restart after receiving a SIGKILL or debug this at least?

**Comment by skarnet** [comment] 2024-07-27 03:15
Yeah, so:

- You first write a support request to my personal e-mail address.
- Then you try to subscribe to the supervision mailing-list, and despite being told that your subscription will be processed manually, you don't wait for the approval
- So you open an issue here, despite github *not* being an official support channel for s6
- Apparently you're using s6-overlay, which *does* use Github as its official support channel, but you did not want to open an issue there?
- You seem to be using s6-overlay v3, which was released in 2022 and had its latest update last June. s6-overlay ships modern version of s6 and associated software. And you're saying you're using a version of s6 from 2021.

I don't know, man. I'm not sure the problem is where you say it is.

**Comment by p01arbear** [comment] 2024-07-30 21:18
The problem was in the my s6-overlay scripts. :facepalm: 

> * You first write a support request to my personal e-mail address.
> * Then you try to subscribe to the supervision mailing-list, and despite being told that your subscription will be processed manually, you don't wait for the approval
> * So you open an issue here, despite github _not_ being an official support channel for s6

Yes, I think that there is nothing criminal about writing to the mailing list and to a github issue at the same time.
It's not said [here](https://github.com/skarnet/s6#:~:text=the%20INSTALL%20file.%0A%0A%0A*-,contact%20information,--------------------%0A%0A%20Laurent%20Bercot%20%3Cska) or [here](https://skarnet.org/lists/) that users shouldn't do that. Regarding to the personal email: sorry to bother you. I rushed.

Thank you!

**Closed** 2024-07-30 21:18 UTC
